# Generated by Django 5.2 on 2025-04-20 11:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_securitynews'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('east', 'Eastern African Region'), ('west', 'Western African Region'), ('north', 'Northern African Region'), ('central', 'Central African Region'), ('south', 'Southern African Region')], max_length=10)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='regional/thumbnails/')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('related', models.ManyToManyField(blank=True, to='main.regionalarticle')),
            ],
        ),
    ]
