# Generated by Django 5.2 on 2025-04-20 14:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_regionalarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture & Agribusiness'), ('mining_energy', 'Mining & Energy'), ('technology', 'Technology & Fintech'), ('infrastructure', 'Infrastructure & Logistics'), ('sustainable', 'Sustainable Business Practices'), ('market_entry', 'Market Entry Strategies'), ('risk_management', 'Risk Management'), ('market_trends', 'Market Trends & Analysis'), ('emerging_industries', 'Emerging Industries'), ('case_studies', 'Case Studies')], help_text='Select the business category', max_length=20)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='business/thumbnails/')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('related', models.ManyToManyField(blank=True, to='main.businessarticle')),
            ],
        ),
    ]
