# Generated by Django 5.2 on 2025-04-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_businessarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
