# Generated by Django 5.2 on 2025-04-19 21:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('regional', 'Regional Security Alerts'), ('cyber', 'Cybersecurity Threats'), ('business_risk', 'Business Risk & Mitigation'), ('policy', 'Government & Policy Updates'), ('fraud', 'Fraud & Scams'), ('breach', 'Data Breaches & Privacy'), ('infra', 'Infrastructure & Critical Systems'), ('intel', 'Surveillance & Intelligence'), ('innovation', 'Tech & Security Innovations in Africa'), ('terror', 'Terrorism & Insurgency'), ('partners', 'Security Partnerships & Collaborations'), ('emergency', 'Emergency Response & Disaster Preparedness'), ('compliance', 'Regulatory Compliance & Legal Risks')], max_length=50)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='security/thumbnails/')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('related', models.ManyToManyField(blank=True, to='main.securitynews')),
            ],
        ),
    ]
