# Generated by Django 5.2 on 2025-04-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshippost',
            name='category',
        ),
        migrations.DeleteModel(
            name='ScholarshipCategory',
        ),
        migrations.DeleteModel(
            name='ScholarshipPost',
        ),
    ]
