# Generated by Django 5.2 on 2025-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_remove_scholarshippost_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='Full news article content (HTML allowed)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('video_url', models.URLField(blank=True, help_text='Optional video URL', null=True)),
                ('region', models.CharField(choices=[('east', 'East Africa'), ('west', 'West Africa'), ('north', 'North Africa'), ('south', 'Southern Africa'), ('central', 'Central Africa')], default='east', max_length=10)),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
