# Generated by Django 5.2 on 2025-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='video_url',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
