# Generated by Django 5.2 on 2025-04-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_newsarticle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='cover_media',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='region',
            field=models.CharField(choices=[('east', 'East Africa'), ('west', 'West Africa'), ('north', 'North Africa'), ('south', 'Southern Africa'), ('central', 'Central Africa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
